---

 - name: play1
   hosts: all
   become: true
   tasks:

   - name: ping servers
     action: ping

   - name: Output System Summary
     shell: free -m
     register: ram_usage

   - name: Print RAM usage
     debug:
       var: ram_usage

   - name: Install Git
     apt:
       name: git
       state: present
